Working Dockerfile, Minor changes to ./run install ./run test still needs to be fixed

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 
 if [ $1 == 'install' ]; then
-    python3 install/localclone_install.py
+    # python3 install/localclone_install.py         Redundent file
+    pip3 install gitpython
+    pip3 install PyGithub
+    pip3 install requests
+    # cargo update -p -depth = 1 ignore --precise 0.4.18                   
+    echo "Install Complete!"
 elif [ $1 == 'build' ]; then 
     cargo build;
 elif [ $1 == 'clean' ]; then 
@@ -12,4 +17,6 @@ elif [ $1 == 'test' ]; then
     python3 test_suite/test_suite_script.py
 else
     ./target/debug/main "$@"
+    # echo "Invalid Input";
+    # exit 5
 fi
